### ISSUE TITLE
Need audio upload by url

### ISSUE THREAD

**Issue by umair321** [AlexJuca/SpectrumVisualizer#1]
Hey, great work you did but Can you please make only visualization by reading file url?

**Comment by AlexJuca** [comment]
_I am not sure what you mean. Do you want to load an audio file by just
passing an url?_

**Comment by umair321** [comment]
Yes, that's what I want :)

**Comment by alexsavage1** [comment]
Hi I was kinda looking for the same thing, but can I have it where the url of the song is already specified then this all starts like autoplay once page is loaded

**Comment by RobertJGabriel** [comment]
Bump

**Comment by AlexJuca** [comment]
Hey sorry for the delay. Just added some code to load your prefered song by
url. :)

I can push the code to gihub if you are still interested in it.

2016-12-19 18:15 GMT+01:00 Robert James Gabriel <notifications@github.com>:

**Comment by alexsavage1** [comment]
Yeah that would be good

**Comment by AlexJuca** [comment]
The v2 branch of this repo has this functionality. You have to specify the url in the visualizer.js file.

**Comment by AlexJuca** [comment]
Now able to play audio stream via url.
